import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../components/core/Providers";
import PrivateRoute from "../components/core/PrivateRoute";
import BarMenu from "@/components/ui/BarMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <PrivateRoute>
            {children}
          </PrivateRoute>
          <BarMenu/>
        </body>
      </Providers>
    </html>
  );
}
